### ISSUE TITLE
请问我怎样才能修改行数区域与右边编辑器区域的颜色?

### ISSUE THREAD

**Issue by luojunyuan** [lyfunny/feel-good#3]
稍微改变一点点颜色，或者使用实线，使他们区分开来
相同颜色有时间一眼看上去，看不出来代码的缩进级别

![image.png](https://i.loli.net/2020/01/23/fpIx39LOaG1Qkeh.png)

**Comment by naivexcited** [comment]
我查了一下VS Code的[官方自定义主题文档](https://code.visualstudio.com/api/references/theme-color)，似乎没有区分这两块地方的颜色的方法。我看了一下其他的一些主题，也没发现这两块颜色不一样的案例。至于中间加实线的方法，我也没有在官方文档中查到。

**Comment by luojunyuan** [comment]
> 我查了一下VS Code的[官方自定义主题文档](https://code.visualstudio.com/api/references/theme-color)，似乎没有区分这两块地方的颜色的方法。我看了一下其他的一些主题，也没发现这两块颜色不一样的案例。至于中间加实线的方法，我也没有在官方文档中查到。

感谢回复！
之前未曾注意到，原来所有主题都是这样的。

再次感谢您的theme，每次装vscode必装这个配色
